In [25]:
import torch
from torch import nn
from d2l import torch as d2l

In [26]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            if mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()

    return Y

In [27]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [28]:
pool2d = nn.MaxPool2d((2, 2), padding=0, stride=1)
pool2d(X)

tensor([[[[ 5.,  6.,  7.],
          [ 9., 10., 11.],
          [13., 14., 15.]]]])

In [29]:
X = torch.cat((X, X + 1), axis=1)
pool2d(X)

tensor([[[[ 5.,  6.,  7.],
          [ 9., 10., 11.],
          [13., 14., 15.]],

         [[ 6.,  7.,  8.],
          [10., 11., 12.],
          [14., 15., 16.]]]])